{{- if .Values.gateway.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "objectio.gateway.fullname" . }}
  labels:
    {{- include "objectio.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "objectio.gateway.fullname" . }}
  minReplicas: {{ .Values.gateway.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.gateway.autoscaling.maxReplicas }}
  metrics:
    {{- if gt (int .Values.gateway.autoscaling.targetCPUUtilizationPercentage) 0 }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.gateway.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if gt (int .Values.gateway.autoscaling.targetMemoryUtilizationPercentage) 0 }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.gateway.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
